//! The gRPC surface: the CSI Identity and Node services, and the kubelet's
//! plugin-registration service.

pub mod identity;
pub mod node;
pub mod registration;

#[allow(
    clippy::all,
    clippy::pedantic,
    clippy::cargo,
    clippy::allow_attributes_without_reason,
    clippy::clone_on_ref_ptr,
    clippy::empty_structs_with_brackets,
    missing_debug_implementations,
    reason = "generated by tonic-prost-build from the .proto files; not edited by hand"
)]
pub mod proto {
    pub mod csi {
        tonic::include_proto!("csi.v1");
    }
    pub mod registration {
        tonic::include_proto!("pluginregistration");
    }
}
