//! The protocol between svidlet and the token issuer.
//!
//! Stage 2 of the roadmap gives OIDC-only relying parties — Azure, hosted
//! services, anything that verifies bearer tokens — a JWT-SVID for a workload, minted by
//! a small central issuer from the workload's X.509-SVID. svidlet asks on the
//! pod's behalf and writes the token into the pod's volume beside `tls.crt`.
//!
//! This crate is what both ends share, and nothing else, so the node side
//! links none of the issuer's key handling or chain verification:
//!
//! - [`proto`]: the gRPC API, client and server.
//! - [`pop`]: the proof that the caller holds the pod's private key, not just
//!   a copy of its (public) certificate.
//! - [`Audience`] and [`parse_audiences`]: what a pod may put in its volume's
//!   `audiences` attribute, and the file each token is written to.
//! - [`Claims`]: the token's payload, for reading an issued token back.
//!
//! The issuer itself is `svidlet-token-issuer`.

#![forbid(unsafe_code)]

mod audience;
mod claims;
pub mod pop;

#[doc(inline)]
pub use audience::{parse_audiences, Audience, AudienceError, MAX_AUDIENCES};
#[doc(inline)]
pub use claims::{Claims, ClaimsError};

/// The gRPC API, generated from `proto/token.proto`.
#[allow(
    clippy::all,
    clippy::pedantic,
    clippy::cargo,
    clippy::allow_attributes_without_reason,
    clippy::clone_on_ref_ptr,
    clippy::empty_structs_with_brackets,
    missing_debug_implementations,
    reason = "generated by tonic-prost-build from token.proto; not edited by hand"
)]
pub mod proto {
    tonic::include_proto!("svidlet.token.v1");
}
